services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml", "--host", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    init: true
    networks:
      - app_network
    restart: always
  opencustoms:
    image: francoischastel/opencustomsgpt:latest
    container_name: opencustoms
    depends_on:
      - litellm
    env_file:
      - .env
    ports:
      - 8501:8501
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    init: true
    restart: always
    

networks:
  app_network:
    driver: bridge
